Cake 3.8 update
bedita/manager pull request #316
Opened 2019-07-28 12:07 UTC by stefanorosanelli

2019-07-30 10:15 UTC, batopa requested changes

2019-07-30 10:15 UTC, batopa commented on src/Application.php
> +                    // Catch any exceptions in the lower layers,
minor: remove extra spaces

2019-07-30 10:15 UTC, batopa commented on src/Application.php
> +            // Token check will be skipped when callback returns `true`.
[minor] extra spaces

2019-07-30 10:15 UTC, batopa commented on src/Application.php
> +            $actions = (array)Configure::read(sprintf('CrsfExceptions.%s', $request->getParam('controller')));
Maybe we could avoid CSRF skip using `X-CSRF-Token` in ajax request, see https://book.cakephp.org/3.0/en/controllers/middleware.html#csrf-protection-and-ajax-requests

I didn't understand if it is our case :upside_down_face:

2019-07-30 10:47 UTC, stefanorosanelli commented on src/Application.php
> +                    // Catch any exceptions in the lower layers,
done

2019-07-30 10:47 UTC, stefanorosanelli commented on src/Application.php
> +            // Token check will be skipped when callback returns `true`.
done

2019-07-30 10:51 UTC, didoda commented on src/Template/Element/json_meta_config.ctp
> +        $csrfToken = json_encode($this->request->getParam('_csrfToken'));
typo?
it should be `$csrfToken = json_encode($this->request->getData('_csrfToken'));` or somethink like that...

2019-07-31 12:32 UTC, batopa approved these changes

2019-08-05 12:04 UTC, didoda approved these changes

2019-09-10 08:46 UTC, merged