Remote url in related media objects
bedita/manager pull request #327
Opened 2019-09-20 12:33 UTC by didoda

Ref: #312

2019-10-24 15:18 UTC, stefanorosanelli requested changes
Adding a `video` via URL embed in a relation `title` attribute of video is not loaded, instead in single video creation via URL embed `title` is correctly set.

Other fields like `provide *` are instead correctly loaded

2019-10-24 15:18 UTC, stefanorosanelli commented on src/Template/Layout/js/app/components/relation-view/relations-add.js
> +            return right.includes('video') || right.includes('media');
`videos` instead of `video`

2019-10-25 06:17 UTC, didoda commented
> Adding a `video` via URL embed in a relation `title` attribute of video is not loaded, instead in single video creation via URL embed `title` is correctly set.
> 
> Other fields like `provide *` are instead correctly loaded

I'll check it... ;)

2019-10-25 09:19 UTC, stefanorosanelli approved these changes

2019-10-25 09:28 UTC, merged