issue/334 feat: video thumbnail added in relation boxes
bedita/manager pull request #345
Opened 2019-11-05 15:39 UTC by nikazzio

resolve #334

2019-11-05 15:48 UTC, didoda approved these changes

2019-11-05 17:25 UTC, stefanorosanelli requested changes

2019-11-05 17:25 UTC, stefanorosanelli commented on src/Template/Element/Form/children.twig
> +                        <div class="thumbnail" v-if="related.type === 'images'" >
Once bedita/bedita#1632 is merged we can rely on `related.meta.thumb_url` as the only condition, no need to check for `images` of `videos` type.

2019-11-05 17:25 UTC, stefanorosanelli commented on src/Template/Element/Form/children.twig
> +                            <figure v-if="related.meta && related.meta.thumb_url">
Make sure to use always `related.meta && related.meta.thumb_url` as condition, not just `related.meta.thumb_url`

2019-11-06 11:02 UTC, stefanorosanelli approved these changes

2019-11-06 11:29 UTC, merged