feat: display simple map for objects with POINT coordinates
bedita/manager pull request #356
Opened 2019-11-25 11:55 UTC by xho

2019-11-25 12:05 UTC, stefanorosanelli requested changes

2019-11-25 12:05 UTC, stefanorosanelli commented on .gitignore
> +/webroot/css/app.css
`/webroot/css/app.*`
`/webroot/css/*.map`
`/webroot/css/vendors/async`

2019-11-25 12:05 UTC, stefanorosanelli commented on src/Template/Layout/default.twig
> +    {# {{ Html.css(['vendors/mapbox.css'], {
remove commented code

2019-11-25 14:20 UTC, stefanorosanelli approved these changes

2019-11-26 12:58 UTC, didoda commented on src/Template/Layout/js/app/components/map-view.js
> + * @prop {String} popup (HTML content)
typo: `popupHtml`

2019-11-26 12:59 UTC, didoda approved these changes

2019-11-28 09:41 UTC, stefanorosanelli approved these changes

2019-11-28 09:41 UTC, merged