Cakephp 4.4.0
bedita/manager pull request #789
Opened 2022-06-08 07:07 UTC by didoda

This updates `cakephp/cakephp` to `4.4.0`.

`cakephp/console` is added in `require-dev` (console classes are not in `cakephp/cakephp:4.4.0`).

2022-06-08 17:35 UTC, stefanorosanelli approved these changes

2022-06-09 09:57 UTC, batopa requested changes

2022-06-09 09:57 UTC, batopa commented on config/bootstrap.php
> +    (new ExceptionTrap(Configure::read('Error')))->register();
I think it would be set both for cli and not, see https://github.com/cakephp/app/blob/4.x/config/bootstrap.php#L125

I would do a double check against cakephp/app to see if other changes on main files (`boostrap.php`, `bootstrap-cli.php`, `app.php`, `paths.php', `Application.php` etc...) can be ported

2022-06-09 13:27 UTC, batopa approved these changes

2022-06-09 13:48 UTC, merged