Roles Modules accesses admin page
bedita/manager pull request #844
Opened 2022-09-12 11:12 UTC by didoda

This provides https://github.com/bedita/manager/issues/842, Roles Modules accesses admin page

2022-09-22 13:47 UTC, stefanorosanelli requested changes
After a quick test:

* `admin` should be excluded in roles list, setting permissions is not effective anyway 

* roles not able to access the Manager app should also be excluded, maybe we could use a configuration for that or better you could find out roles looking at endpoint permissions on `/auth` endpoint, maybe not that simple  

* we should show if some modules-endpoints are already filtered via endpoint permissions (not easy, we can do this later), otherwise some permission here could be not effective (e.g. a module already readonly for a role via endpoint permissions) 

* in roles list we could simply display `manager` instead `manager 2 Manager Role` 

* when a module is read only (via endpoint permissions or manager ACL) an icon or some visual element coudl be useful (TODO in other issue)

2022-09-26 15:02 UTC, stefanorosanelli commented on src/Template/Element/Admin/sidebar.twig
> +{% set actions = ['appearence', 'applications', 'endpoints', 'config', 'async_jobs', 'roles', 'roles_modules', 'endpoint_permissions'] %}
Probably a better link label is `Modules Access` or `Modules ACL` - we can chenge it later

2022-09-26 15:02 UTC, stefanorosanelli approved these changes

2022-09-28 09:39 UTC, didoda commented on src/Template/Element/Admin/sidebar.twig
> +{% set actions = ['appearence', 'applications', 'endpoints', 'config', 'async_jobs', 'roles', 'roles_modules', 'endpoint_permissions'] %}
We'll do it later

2022-09-28 09:41 UTC, merged